import { GlobalSettings } from "./types";

export const DEFAULT_SETTINGS: GlobalSettings = {
  depositPercent: 30,
  platformFeePercent: 2.5,
  passPlatformFeeToCustomer: false,
  currency: "GBP",
  taxEnabled: false,
  taxPercent: 0,
  deliveryEnabled: true,
  labourEnabled: true,
  discountEnabled: true,
  setupFeeEnabled: true,
  takedownFeeEnabled: true,
  defaultDeliveryMode: "none",
  defaultRoundTrip: true,
  defaultHourlyRate: 0,
  aiTokensIncluded: 0,
  aiTokensUsed: 0,
  mockupTokensIncluded: 0,
  mockupTokensUsed: 0,
  defaultUnit: "ft",
  defaultDistanceUnit: "miles",
  tiers: [
    {
      id: "tier-1",
      name: "Tier 1",
      pricePerFt: 15,
      pricePerM: 49,
      description: "Base tier",
      active: true,
      sortOrder: 1,
    },
    {
      id: "tier-2",
      name: "Tier 2",
      pricePerFt: 22,
      pricePerM: 72,
      description: "Mid tier",
      active: true,
      sortOrder: 2,
    },
    {
      id: "tier-3",
      name: "Tier 3",
      pricePerFt: 35,
      pricePerM: 115,
      description: "Premium tier",
      active: true,
      sortOrder: 3,
    },
  ],
  addons: [
    {
      id: "addon-cake-stand",
      name: "Cake Stand",
      price: 45,
      category: "Accessories",
      active: true,
      sortOrder: 1,
    },
    {
      id: "addon-led-number-set",
      name: "LED Number Set",
      price: 60,
      category: "Lighting",
      active: true,
      sortOrder: 2,
    },
    {
      id: "addon-character-cutout",
      name: "Character Cutout",
      price: 35,
      category: "Accessories",
      active: true,
      sortOrder: 3,
    },
    {
      id: "addon-shimmer-wall",
      name: "Shimmer Wall",
      price: 150,
      category: "Backdrops",
      active: true,
      sortOrder: 4,
    },
    {
      id: "addon-neon-sign",
      name: "Neon Sign",
      price: 85,
      category: "Lighting",
      active: true,
      sortOrder: 5,
    },
    {
      id: "addon-setup-takedown",
      name: "Setup & Takedown",
      price: 80,
      category: "Service",
      active: true,
      sortOrder: 6,
    },
  ],
  delivery: {
    homeAddress: "",
    freeRadiusMiles: 10,
    freeRadiusKm: 16,
    costPerMile: 1.5,
    costPerKm: 0.93,
    minimumFee: 20,
    setupFee: 0,
    takedownFee: 0,
  },
};
